review App Onboarding and Overview content
cb-suryak/cb-partner-mintlify-spi pull request #9
Opened 2024-12-04 06:18 UTC by cb-suryak

2024-12-04 12:27 UTC, cb-sabuj requested changes
@cb-suryak I have reviewed the content. Overall content will be reviewed by @cb-umerhafeezmir once again, so that we do not miss anything.

2024-12-04 12:27 UTC, cb-sabuj commented on app-onboarding/guide.mdx
> +  - The app must have the capability to effectively handle **concurrent requests** to ensure smooth operation during peak loads.
```
7. **Concurrency Handling**
  - Ensure your application can handle **concurrent requests** effectively for seamless operation during peak loads.
```

2024-12-05 04:39 UTC, cb-umerhafeezmir commented on api-reference/v1/Overview.mdx
> +Our **Partner SPIs** are designed to enable seamless integration with Chargebee, empowering partners to extend and enhance our platform's capabilities. These SPIs provide a standardized interface for
exceptional _user _experience__.

2024-12-05 04:41 UTC, cb-umerhafeezmir commented on api-reference/v1/Overview.mdx
> +Our SPIs are built with scalability and ease of integration in mind, enabling partners to deliver specialized functionality tailored to Chargebee's diverse customer base.y and ease of integration in
Add this section to the **Overview** part before we talk about the Key features.

2024-12-05 04:42 UTC, cb-sabuj commented on api-reference/v1/Overview.mdx
> +Our **Partner SPIs** are designed to enable seamless integration with Chargebee, empowering partners to extend and enhance our platform's capabilities. These SPIs provide a standardized interface for
Changed it @cb-umerhafeezmir

2024-12-05 04:45 UTC, cb-umerhafeezmir commented on api-reference/v1/tax_spi/Overview.mdx
> +To streamline tax management during checkout sessions and invoice creation, Chargebee performs several key operations, including:
The page heading already has Overview in it.
Write the second heading as **Tax SPI Integration**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/3852b39f-b033-4ccb-9ec6-e488dc4482d4">

2024-12-05 04:47 UTC, cb-umerhafeezmir commented on api-reference/v1/tax_spi/Overview.mdx
> +Ensuring shipping addresses are valid for accurate tax calculation and product delivery.
**Validating Customer Shipping Address:** Validates shipping addresses to ensure accurate tax calculation and product delivery.

2024-12-05 04:57 UTC, cb-shishiryadav commented on api-reference/v1/Overview.mdx
> +Our **Partner SPIs** are designed to enable seamless integration with Chargebee, empowering partners to extend and enhance our platform's capabilities. These SPIs provide a standardized interface for
Done

2024-12-05 04:58 UTC, cb-umerhafeezmir commented on api-reference/v1/docs/Authorization.mdx
> +Chargebee employs **HTTP header-based authorization** for all API endpoints related to the Service Adapter. This ensures secure and dynamic management of authorization credentials during API interact
Hyperlink the HTTP header-based authorization to[ IETF docs ](https://datatracker.ietf.org/doc/html/rfc7235)

2024-12-05 04:58 UTC, cb-shishiryadav commented on api-reference/v1/Overview.mdx
> +   Effortlessly integrate your tax computation services to ensure compliance and accuracy in real-time.
Done

2024-12-05 04:59 UTC, cb-shishiryadav commented on api-reference/v1/Overview.mdx
> +   Validate tax registration numbers instantly to streamline customer onboarding and compliance processes.
Done

2024-12-05 07:15 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +  - Merchant-specific confidential data shared with partner app servers must be handled securely and in compliance with PII requirements.
Link to the PII requirements doc.

2024-12-05 07:16 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +  - A formal legal contract must be signed between Chargebee and the partner app to establish clear terms and conditions.
Link to how to sign a legal agreement? Probably support team link?

2024-12-05 07:18 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +  - **Note**: Uninformed downtimes may lead to the app being **delisted** from the marketplace.
Would they need to create a status page for displaying uptime in real-time?

2024-12-05 07:21 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +  - This capacity will be tested during integration, and it is recommended to ensure the app adheres to this limit.
@cb-suryak @cb-sabuj The rate limits on the [Chargebee API docs](https://apidocs.chargebee.com/docs/api/error-handling?lang=curl#api_rate_limits) are different than what is suggested here. Is there a discrepancy or are we maintaining different rate limits for the SPI?

2024-12-05 07:23 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +  - Fill the configuration and capabilities details of your app [here](https://tinyurl.com/cb-partner-app-registration) and generate the JSON.
Fill the configuration and **capability** details ........

2024-12-05 07:25 UTC, cb-umerhafeezmir commented on app-onboarding/guide.mdx
> +- **Promotion**: Leverage Chargebee’s marketing channels to reach a broader audience of merchants.
Remove this "**of merchants**"

2024-12-05 07:27 UTC, cb-umerhafeezmir commented on development.mdx
> +Step 2. Go to the docs are located (where you can find `mint.json`) and run the following command:
typo " **are located**"

2024-12-05 07:32 UTC, cb-umerhafeezmir commented on api-reference/v1/docs/fetch-the-health-status-of-the-service-provider.md
> +A successful response with a status code of `200` indicates that the service is healthy. The response will include the overall status and details of individual components.
Instead of **Fetch** use **Retrieves** where ever applicable.
@cb-suryak

2024-12-05 07:35 UTC, cb-umerhafeezmir commented on api-reference/v1/tax_reg_number_validate/TestingwithPostman.mdx
> +Now, you're ready to interact with Tax Registration Number SPI endpoints using Postman. Refer to the [Tax Registration Validation SPI Reference](https://www.chargebee.com/docs/api-reference/v1/tax_re
We need to write this section better.
Maybe we can take inspiration from the [BQE Core Postman](https://api-explorer.bqecore.com/docs/develop/postman) docs.

@cb-suryak

2024-12-05 10:04 UTC, cb-shishiryadav commented
@cb-sabuj @cb-umerhafeezmir I made changes that you have suggested and raised a pr. Just a couple of changes left like Testing with Postman in which I need @cb-suryak assistance.

2024-12-06 12:15 UTC, cb-suryak commented on api-reference/v1/tax_reg_number_validate/TestingwithPostman.mdx
> +Now, you're ready to interact with Tax Registration Number SPI endpoints using Postman. Refer to the [Tax Registration Validation SPI Reference](https://www.chargebee.com/docs/api-reference/v1/tax_re
sure.

2024-12-06 12:16 UTC, cb-suryak commented on app-onboarding/guide.mdx
> +- **Promotion**: Leverage Chargebee’s marketing channels to reach a broader audience of merchants.
done

2024-12-06 12:26 UTC, cb-suryak commented on api-reference/v1/docs/Authorization.mdx
> +    - **`is_sensitive`**: Indicates whether the credential is sensitive.
done

2024-12-06 13:02 UTC, cb-suryak commented on app-onboarding/guide.mdx
> +  - This capacity will be tested during integration, and it is recommended to ensure the app adheres to this limit.
Updated with Chargebee ratelimiting link. Removed the numbers configured here.

2024-12-14 07:38 UTC, cb-suryak commented on app-onboarding/guide.mdx
> +  - Merchant-specific confidential data shared with partner app servers must be handled securely and in compliance with PII requirements.
will attach the chargbee's official security page that talks about PII

2024-12-14 07:48 UTC, cb-suryak commented on app-onboarding/guide.mdx
> +  - A formal legal contract must be signed between Chargebee and the partner app to establish clear terms and conditions.
will have to understand the current process and update it. Wil keep this open.

2024-12-14 07:49 UTC, cb-suryak commented on api-reference/v1/tax_reg_number_validate/TestingwithPostman.mdx
> +Now, you're ready to interact with Tax Registration Number SPI endpoints using Postman. Refer to the [Tax Registration Validation SPI Reference](https://www.chargebee.com/docs/api-reference/v1/tax_re
we will revise this in the upcomign weeks.

2025-02-05 06:22 UTC, closed without merging